In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
print(type(arr1))
print(arr1)
print(arr1.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)


In [8]:
arr1=arr1.reshape(1,5)
print(arr1.shape)

(1, 5)


In [12]:
arr2=np.arange(2,11,2).reshape(1,5)
arr2

array([[ 2,  4,  6,  8, 10]])

In [24]:
arr3=np.random.randint(low=11,high=22,size=(1,5))
arr3

array([[17, 12, 20, 17, 14]])

In [35]:
arr4=np.ones((1,5))
print(arr4)
arr5=np.zeros((1,5))
print(arr5)
arr6=np.eye(3)
print(arr6)
arr7=np.full((1,5),2)
print(arr7)

[[1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2 2 2 2 2]]


In [39]:
print(np.sum(arr3))
print(np.mean(arr3))
print(np.std(arr3))
print(np.median(arr3))
print(np.var(arr3))

80
16.0
2.756809750418044
17.0
7.6


In [40]:
arr1+arr2

array([[ 3,  6,  9, 12, 15]])

In [43]:
print(arr3)
print(arr1)
arr3[(arr1)>4]

[[17 12 20 17 14]]
[[1 2 3 4 5]]


array([14])